In [2]:
#importamos las librerias
import pandas as pd
import json
import warnings
warnings.filterwarnings("ignore")

In [4]:
#Se extraen los datos desde el archivo 'steam_games.json', se convierte en Dataframe y se guarda como csv

with open('D:\Desktop\proyecto entrega 1\json\output_steam_games.json', 'r', encoding='utf-8') as archivo:
   steam = [json.loads(line) for line in archivo]

#Convertirlo a DataFrame
out_steam = pd.DataFrame(steam)

#Guardar el Dataframe como csv
out_steam.to_csv("steam.csv", index=False)

print("OK")

OK

In [3]:
#VisualizaciÃ³n del DataFrame
out_steam

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"[Casual, Indie, Simulation, Strategy]",Colony On Mars,Colony On Mars,http://store.steampowered.com/app/773640/Colon...,2018-01-04,"[Strategy, Indie, Casual, Simulation]",http://steamcommunity.com/app/773640/reviews/?...,"[Single-player, Steam Achievements]",1.99,False,773640,"Nikita ""Ghost_RUS"""
120441,Sacada,"[Casual, Indie, Strategy]",LOGistICAL: South Africa,LOGistICAL: South Africa,http://store.steampowered.com/app/733530/LOGis...,2018-01-04,"[Strategy, Indie, Casual]",http://steamcommunity.com/app/733530/reviews/?...,"[Single-player, Steam Achievements, Steam Clou...",4.99,False,733530,Sacada
120442,Laush Studio,"[Indie, Racing, Simulation]",Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich
120443,SIXNAILS,"[Casual, Indie]",EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns"
120444,NaN,NaN,Maze Run VR,NaN,http://store.steampowered.com/app/681550/Maze_...,NaN,"[Early Access, Adventure, Indie, Action, Simul...",http://steamcommunity.com/app/681550/reviews/?...,"[Single-player, Stats, Steam Leaderboards, HTC...",4.99,True,681550,NaN

In [4]:
#Analisis de los valores nulos y los tipos de datos

def info_nulos(dataframe):
    datos = {"Columna": [], "tipo_de_dato": [], "%_no_nulos": [], "%_nulos": [], "nulos": []}

    for columna in dataframe.columns:
        no_nulos = (dataframe[columna].count() / len(dataframe)) * 100
        datos["Columna"].append(columna)
        datos["tipo_de_dato"].append(dataframe[columna].apply(type).unique())
        datos["%_no_nulos"].append(round(no_nulos, 2))
        datos["%_nulos"].append(round(100-no_nulos, 2))
        datos["nulos"].append(dataframe[columna].isnull().sum())

    df_info = pd.DataFrame(datos)
        
    return df_info

info_nulos(out_steam)

,Columna,tipo_de_dato,%_no_nulos,%_nulos,nulos
0,publisher,"[<class 'float'>, <class 'str'>]",20.00,80.00,96362
1,genres,"[<class 'float'>, <class 'list'>]",23.95,76.05,91593
2,app_name,"[<class 'float'>, <class 'str'>]",26.68,73.32,88312
3,title,"[<class 'float'>, <class 'str'>]",24.98,75.02,90360
4,url,"[<class 'float'>, <class 'str'>]",26.68,73.32,88310
5,release_date,"[<class 'float'>, <class 'str'>]",24.96,75.04,90377
6,tags,"[<class 'float'>, <class 'list'>]",26.54,73.46,88473
7,reviews_url,"[<class 'float'>, <class 'str'>]",26.68,73.32,88312
8,specs,"[<class 'float'>, <class 'list'>]",26.12,73.88,88980
9,price,"[<class 'float'>, <class 'str'>]",25.54,74.46,89687
10,early_access,"[<class 'float'>, <class 'bool'>]",26.68,73.32,88310
11,id,"[<class 'float'>, <class 'str'>]",26.68,73.32,88312
12,developer,"[<class 'float'>, <class 'str'>]",23.94,76.06,91609

In [5]:
#eliminamos los archivos NaN
out_steam= out_steam.dropna(how='all').reset_index(drop=True)
out_steam.shape

(32135, 13)

In [7]:
#La columna ID deben ser valores unicos, se procede a revisar si hay duplicados
out_steam[out_steam['id'].duplicated()]

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
14573,Bethesda Softworks,[Action],Wolfenstein II: The New Colossus,Wolfenstein II: The New Colossus,http://store.steampowered.com/app/612880/Wolfe...,2017-10-26,"[Action, FPS, Gore, Violent, Alternate History...",http://steamcommunity.com/app/612880/reviews/?...,"[Single-player, Steam Achievements, Full contr...",59.99,False,612880,Machine Games
30961,"Warner Bros. Interactive Entertainment, Feral ...","[Action, Adventure]",Batman: Arkham City - Game of the Year Edition,Batman: Arkham City - Game of the Year Edition,http://store.steampowered.com/app/200260,2012-09-07,"[Action, Open World, Batman, Adventure, Stealt...",NaN,"[Single-player, Steam Achievements, Steam Trad...",19.99,False,NaN,"Rocksteady Studios,Feral Interactive (Mac)"

In [8]:
#Se encuentran pocos duplicados y se deciden eliminar
indices = [14573,30961]
out_steam = out_steam.drop(indices)

# Transformacion columnas

In [9]:
out_steam['publisher'] = out_steam['publisher'].astype(str)  # se convierten a string los valores
out_steam[ 'title'] = out_steam['title'].astype(str)  
out_steam[ 'developer'] = out_steam[ 'developer'].astype(str)

In [10]:
out_steam['publisher'] = out_steam['publisher'].fillna('Sin dato') #se rellenan los valores nulos 
out_steam[ 'title'] = out_steam[ 'title'].fillna('Sin dato') #se rellenan los valores nulos 
out_steam['developer'] = out_steam[ 'developer'].fillna('Sin dato') #se rellenan los valores nulos

In [11]:
def info_nulos(dataframe):
    datos = {"Columna": [], "tipo_de_dato": [], "%_no_nulos": [], "%_nulos": [], "nulos": []}

    for columna in dataframe.columns:
        no_nulos = (dataframe[columna].count() / len(dataframe)) * 100
        datos["Columna"].append(columna)
        datos["tipo_de_dato"].append(dataframe[columna].apply(type).unique())
        datos["%_no_nulos"].append(round(no_nulos, 2))
        datos["%_nulos"].append(round(100-no_nulos, 2))
        datos["nulos"].append(dataframe[columna].isnull().sum())

    df_info = pd.DataFrame(datos)
        
    return df_info

info_nulos(out_steam)

,Columna,tipo_de_dato,%_no_nulos,%_nulos,nulos
0,publisher,[<class 'str'>],100.00,0.00,0
1,genres,"[<class 'list'>, <class 'float'>]",89.78,10.22,3283
2,app_name,"[<class 'str'>, <class 'float'>]",99.99,0.01,2
3,title,[<class 'str'>],100.00,0.00,0
4,url,[<class 'str'>],100.00,0.00,0
5,release_date,"[<class 'str'>, <class 'float'>]",93.57,6.43,2067
6,tags,"[<class 'list'>, <class 'float'>]",99.49,0.51,163
7,reviews_url,"[<class 'str'>, <class 'float'>]",100.00,0.00,1
8,specs,"[<class 'list'>, <class 'float'>]",97.91,2.09,670
9,price,"[<class 'float'>, <class 'str'>]",95.71,4.29,1377
10,early_access,[<class 'bool'>],100.00,0.00,0
11,id,"[<class 'str'>, <class 'float'>]",100.00,0.00,1
12,developer,[<class 'str'>],100.00,0.00,0

In [12]:
#Se procede a completar los valores nulos y convertir a tipo float aquellos que no lo son, previamente asignando el valor 'free to play' a 0.
out_steam['price'] = pd.to_numeric(out_steam['price'], errors='coerce') #pasamos a numerica la columna
out_steam['price'] = out_steam['price'].replace('Free To Play', 0) #se reemplaza por 0 el free to play
out_steam['price'] = out_steam['price'].fillna(0)

In [13]:
out_steam['price'].dtype

dtype('float64')

Al observar el analisis que se debe realizar, se debe trabajar con el aÃ±o solamente, por lo que se sobreescribe, se rellenan los nulos con 0

In [14]:
out_steam['year_release'] = pd.to_datetime(out_steam['release_date'], errors='coerce').dt.year # crea la columna solo con el aÃ±o 
out_steam.head()

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer,year_release
0,Kotoshiro,"[Action, Casual, Indie, Simulation, Strategy]",Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018.0
1,"Making Fun, Inc.","[Free to Play, Indie, RPG, Strategy]",Ironbound,Ironbound,http://store.steampowered.com/app/643980/Ironb...,2018-01-04,"[Free to Play, Strategy, Indie, RPG, Card Game...",http://steamcommunity.com/app/643980/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,643980,Secret Level SRL,2018.0
2,Poolians.com,"[Casual, Free to Play, Indie, Simulation, Sports]",Real Pool 3D - Poolians,Real Pool 3D - Poolians,http://store.steampowered.com/app/670290/Real_...,2017-07-24,"[Free to Play, Simulation, Sports, Casual, Ind...",http://steamcommunity.com/app/670290/reviews/?...,"[Single-player, Multi-player, Online Multi-Pla...",0.00,False,670290,Poolians.com,2017.0
3,å½¼å²¸é¢†åŸŸ,"[Action, Adventure, Casual]",å¼¹ç‚¸äºº2222,å¼¹ç‚¸äºº2222,http://store.steampowered.com/app/767400/2222/,2017-12-07,"[Action, Adventure, Casual]",http://steamcommunity.com/app/767400/reviews/?...,[Single-player],0.99,False,767400,å½¼å²¸é¢†åŸŸ,2017.0
4,nan,NaN,Log Challenge,nan,http://store.steampowered.com/app/773570/Log_C...,NaN,"[Action, Indie, Casual, Sports]",http://steamcommunity.com/app/773570/reviews/?...,"[Single-player, Full controller support, HTC V...",2.99,False,773570,nan,NaN

In [15]:
# Se obtiene la cantidad de apariciones de cada valor en 'release_year'
conteo_valores = out_steam['year_release'].value_counts()

# Se muestra los valores y sus conteos
print(conteo_valores)

year_release
2017.0    9517
2016.0    6933
2015.0    4945
2014.0    2832
2013.0    1551
2012.0    1191
2011.0     589
2010.0     436
2009.0     337
2008.0     213
2007.0     167
2006.0     155
2005.0     102
2018.0      96
2003.0      84
2004.0      79
2001.0      69
1998.0      61
1999.0      55
2002.0      50
1997.0      42
2000.0      40
1996.0      39
1994.0      36
1993.0      34
1995.0      33
1991.0      16
1992.0      15
1990.0      12
1989.0      10
1987.0       9
1988.0       7
1984.0       4
1983.0       4
1985.0       3
1982.0       3
1981.0       3
2019.0       3
1970.0       2
1986.0       1
2021.0       1
1975.0       1
1980.0       1
Name: count, dtype: int64

In [16]:
cantidad_nulos = out_steam['year_release'].isnull().sum()
cantidad_nulos

2352

In [17]:
out_steam['year_release'].describe()

count    29781.000000
mean      2014.759175
std          3.508269
min       1970.000000
25%       2014.000000
50%       2016.000000
75%       2017.000000
max       2021.000000
Name: year_release, dtype: float64

In [18]:
#Rellenamos los valores nulos con la media de los datos
out_steam['year_release'] = out_steam['year_release'].fillna(2015) 
out_steam['year_release'] = out_steam['year_release'].astype(int)

**Columna Genres**

Se observa que hay varias filas con una lista como genero, debido a esto y para tener un mejor analisis, se requiere expandir la columna con una columna por genero

In [19]:
out_steam = out_steam.explode("genres")
out_steam= out_steam.dropna(subset=["genres"])

In [20]:
out_steam

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer,year_release
0,Kotoshiro,Action,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
0,Kotoshiro,Casual,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
0,Kotoshiro,Indie,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
0,Kotoshiro,Simulation,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
0,Kotoshiro,Strategy,Lost Summoner Kitty,Lost Summoner Kitty,http://store.steampowered.com/app/761140/Lost_...,2018-01-04,"[Strategy, Action, Indie, Casual, Simulation]",http://steamcommunity.com/app/761140/reviews/?...,[Single-player],4.99,False,761140,Kotoshiro,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32132,Laush Studio,Indie,Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich,2018
32132,Laush Studio,Racing,Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich,2018
32132,Laush Studio,Simulation,Russian Roads,Russian Roads,http://store.steampowered.com/app/610660/Russi...,2018-01-04,"[Indie, Simulation, Racing]",http://steamcommunity.com/app/610660/reviews/?...,"[Single-player, Steam Achievements, Steam Trad...",1.99,False,610660,Laush Dmitriy Sergeevich,2018
32133,SIXNAILS,Casual,EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns",2017
32133,SIXNAILS,Indie,EXIT 2 - Directions,EXIT 2 - Directions,http://store.steampowered.com/app/658870/EXIT_...,2017-09-02,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",http://steamcommunity.com/app/658870/reviews/?...,"[Single-player, Steam Achievements, Steam Cloud]",4.99,False,658870,"xropi,stev3ns",2017

Se eliminan columnas debido a que no sera utilizadas en el modelo ni funciones

In [21]:
out_steam= out_steam.drop(['publisher','app_name', 'url', 'release_date','tags', 'reviews_url', 'specs', 'early_access', 'price'], axis=1)
out_steam.columns

Index(['genres', 'title', 'id', 'developer', 'year_release'], dtype='object')

In [22]:
def info_nulos(dataframe):
    datos = {"Columna": [], "tipo_de_dato": [], "%_no_nulos": [], "%_nulos": [], "nulos": []}

    for columna in dataframe.columns:
        no_nulos = (dataframe[columna].count() / len(dataframe)) * 100
        datos["Columna"].append(columna)
        datos["tipo_de_dato"].append(dataframe[columna].apply(type).unique())
        datos["%_no_nulos"].append(round(no_nulos, 2))
        datos["%_nulos"].append(round(100-no_nulos, 2))
        datos["nulos"].append(dataframe[columna].isnull().sum())

    df_info = pd.DataFrame(datos)
        
    return df_info

info_nulos(out_steam)

        Columna     tipo_de_dato  %_no_nulos  %_nulos  nulos
0        genres  [<class 'str'>]       100.0      0.0      0
1         title  [<class 'str'>]       100.0      0.0      0
2            id  [<class 'str'>]       100.0      0.0      0
3     developer  [<class 'str'>]       100.0      0.0      0
4  year_release  [<class 'int'>]       100.0      0.0      0

In [23]:
out_steam

,genres,title,id,developer,year_release
0,Action,Lost Summoner Kitty,761140,Kotoshiro,2018
0,Casual,Lost Summoner Kitty,761140,Kotoshiro,2018
0,Indie,Lost Summoner Kitty,761140,Kotoshiro,2018
0,Simulation,Lost Summoner Kitty,761140,Kotoshiro,2018
0,Strategy,Lost Summoner Kitty,761140,Kotoshiro,2018
...,...,...,...,...,...
32132,Indie,Russian Roads,610660,Laush Dmitriy Sergeevich,2018
32132,Racing,Russian Roads,610660,Laush Dmitriy Sergeevich,2018
32132,Simulation,Russian Roads,610660,Laush Dmitriy Sergeevich,2018
32133,Casual,EXIT 2 - Directions,658870,"xropi,stev3ns",2017
32133,Indie,EXIT 2 - Directions,658870,"xropi,stev3ns",2017

guardamos el archivo

In [24]:
out_steam.to_csv('Output_Steam_limpia.csv', index=False, encoding='utf-8')
print(f'Se guardÃ³ el archivo ')

Se guardÃ³ el archivo